### ISSUE TITLE
hope to add propBlackList option

### ISSUE THREAD

**Issue by guangfu** [cuth/postcss-pxtorem#25]
sometimes need to ignore some css properties that translates px to rem, such as border. so hope to add propBlackList option

**Comment by sndrs** [comment]
would you be interested in a PR for this?

**Comment by cuth** [comment]
If it doesn't affect performance too much for those that don't use it.

**Comment by sndrs** [comment]
i guess you'd have to use either `propWhiteList` or `propBlackList`, since this wouldn't really make sense:
```js
{
    propWhiteList: ['font'],
    propBlackList: ['font'],
}
```
how about if you leave both of those options off, the default is to remify every prop (the equivalent of  `propWhiteList: ['']` now), if you supply both you get an error, and if you supply one it's observed?

**Comment by sndrs** [comment]
maybe, in the case you tried to supply both options `propWhiteList` would always override `propBlackList`, and you get a warning instead?

**Comment by KayLeung** [comment]
I preferred BlackList always override WhiteList. Usually, I want to blacklist them because that have sub-pixels rendering problem in some cases.

**Comment by cuth** [comment]
In version 4.0.0 you can use a BlackList by just adding a wildcard to the propList:

```js
{
  propList: ['*', '!border*']`
}
```
